version: '2'
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    restart: always

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    restart: always

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always