name: Maven Package
on:
  push:
    branches: ['develop']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configura jdk
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        cache: maven

    - name: Executa testes com Maven
      run: mvn test

    - name: Empacota artefato com Maven
      run: mvn package -DskipTests

    - name: Prepara o artefato para upload
      run: mkdir staging && cp application/target/*.jar staging

    - name: Executa upload do artefato
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging