name: Maven Package
on:
  push:
    branches: ['develop']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        cache: maven

    - name: Build with Maven
      run: mvn package

    - name: Prepare artifact for upload
      run: mkdir staging && cp application/target/*.jar staging

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging